## This manifest deploys CredHub and a co-located PostgreSQL database. This configuration assumes that you have an existing UAA deployed at a known location for authentication. 
## 
## This deployment is intended for development testing only. You will lose all of your stored data in the event of an issue with the VM or mounted disks. 
## 
## This manifest assumes that you are deploying with a BOSH Director that has CredHub enabled. If this is not the case, you must replace the values below with ((variable)) syntax with actual values. If you are using BOSH with CredHub enabled, these values will be generated automatically, with the exception of '/uaa/jwt', which you must set to the public verification key for you UAA provider.
## 
## You must update the vm_type (currently 'medium') and network name (currently 'west') according to your cloud config. You must also replace the external_ip and uaa_url with an accurate values. 
---
name: credhub-postgres

releases:
- name: credhub
  version: latest
- name: postgres
  version: latest

stemcells: 
- alias: default 
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 10
  update_watch_time: 10000-120000
  canary_watch_time: 10000-120000

variables:
- name: credhub/encrypt-key
  type: password
  options: 
    only_hex: true
    length: 32
- name: credhub/tls
  type: certificate 
  options: 
    common_name: *ext
    alternative_names: 
    - *ext
- name: database/admin
  type: password
  options: 
    length: 30
    exclude_special: true

instance_groups: 
- name: credhub-postgres
  instances: 1
  vm_type: medium
  azs: [west]
  stemcell: default
  networks:
  - name: west
    default: [dns, gateway]
  - name: public
    static_ips: [*ext]

  external_ip: &ext "198.51.100.100"
  uaa_url: &uaa "https://uaa.example.com:8443" 

  jobs:
  - name: credhub
    release: credhub
    properties: 
      credhub:
        port: 8844
        data_storage:
          type: postgres
          username: credhub
          password: ((database/admin))
          host: 127.0.0.1
          port: 5432
          database: credhub
        authentication:
          uaa:
            url: *uaa
            verification_key: ((/uaa/jwt.public_key)) 
        tls: ((credhub/tls)) 
        encryption:
          keys: 
          - provider_name: internal
            dev_key: ((credhub/encrypt-key))  
            active: true
          providers: 
          - name: internal 
            type: dev_internal
        log_level: info

  - name: postgres
    release: postgres
    properties: 
      databases:
        address: 127.0.0.1
        port: 5432
        databases: 
        - name: credhub
        roles: 
        - name: credhub 
          password: ((database/admin))
